name: LunarBreakerAPI
version: ${git.commit.id.abbrev}
description: CheatBreaker and Lunar Client API plugin
authors: ["CheatBreaker Development Team", "Moonsworth LLC", "ProPractice"]
main: com.lunarbreaker.api.LunarBreakerAPI
load: STARTUP
commands:
  lc:
    aliases: ["lunarclient"]
  client:
  lunarbreaker:
    aliases: ["lbapi"]
  cb:
    aliases: ["cheatbreaker"]