name: LunarBreakerAPI
version: 25b34e0
description: CheatBreaker and Lunar Client API plugin
authors: ["CheatBreaker Development Team", "Moonsworth LLC", "ProPractice"]
main: com.lunarbreaker.api.LunarBreakerAPI
load: STARTUP
commands:
  lc:
    aliases: ["lunarclient"]
  client:
  lunarbreaker:
  cb:
    aliases: ["cheatbreaker"]